version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prepilot
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@db:5432/prepilot?sslmode=disable
      # Add other env vars as needed
    ports:
      - "8080:8080"
    volumes:
      - ./internal/db/migrations:/app/internal/db/migrations:ro
    # command: ["./server"] # Optional, already set in Dockerfile

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      # If your React app needs to know the backend URL, set it here
      VITE_API_URL: http://localhost:8080
    ports:
      - "5173:80"
    # If you want hot reload in dev, see notes below

volumes:
  db_data:
