ALTER TABLE study_plans
ADD COLUMN IF NOT EXISTS subject_id UUID,
ADD COLUMN IF NOT EXISTS exam_id UUID;

ALTER TABLE study_plans
DROP COLUMN IF EXISTS exam_date,
DROP COLUMN IF EXISTS start_date,
DROP COLUMN IF EXISTS end_date,
DROP COLUMN IF EXISTS subject;
