// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Exam struct {
	ID        uuid.UUID    `json:"id"`
	UserID    string       `json:"user_id"`
	Title     string       `json:"title"`
	SubjectID uuid.UUID    `json:"subject_id"`
	Date      time.Time    `json:"date"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type StudyPlan struct {
	ID          uuid.UUID      `json:"id"`
	UserID      string         `json:"user_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ExamID      uuid.UUID      `json:"exam_id"`
}

type StudyTask struct {
	ID          uuid.UUID      `json:"id"`
	PlanID      uuid.NullUUID  `json:"plan_id"`
	Title       string         `json:"title"`
	DueDate     time.Time      `json:"due_date"`
	IsCompleted sql.NullBool   `json:"is_completed"`
	Priority    sql.NullInt32  `json:"priority"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Subject struct {
	ID        uuid.UUID    `json:"id"`
	UserID    string       `json:"user_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	Name          sql.NullString `json:"name"`
	Email         string         `json:"email"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	ClerkID       string         `json:"clerk_id"`
	FirstName     sql.NullString `json:"first_name"`
	LastName      sql.NullString `json:"last_name"`
	ImageUrl      sql.NullString `json:"image_url"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	LastSignInAt  sql.NullTime   `json:"last_sign_in_at"`
	Banned        sql.NullBool   `json:"banned"`
}
